version: '3.9'
services:
  db:
    image: mysql:8.0.27
    volumes:
      - ./mysql/data:/var/lib/mysql   
    networks:
      - backend
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
  node:
    env_file:
      - .env
    build: .
    restart: always
    networks:
      - backend
    ports:
      - 4002:4002
    volumes:
      - ./log:/home/node/app/log
    environment:
      - MYSQL_HOST=db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
networks:
  backend:
